import { test } from 'node:test';
import type { TestContext } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, mkdir, writeFile, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import * as git from '../src/git.ts';
const exec = promisify(execFile);
test('diffNameOnly는 한글과 공백을 포함한 실제 경로를 반환한다', async t => {
  const cwd = await repo(t);
  await command(cwd, 'config', 'core.quotePath', 'true');
  await writeFile(join(cwd, 'base'), 'base');
  const base = (await git.commitAll(cwd, 'base'))!;
  await mkdir(join(cwd, 'docs/wiki'), { recursive: true });
  const paths = ['a b.txt', 'docs/wiki/검색.md', 'trailing-space ', 'line\nbreak.txt'];
  for (const path of paths) await writeFile(join(cwd, path), 'new');
  const head = (await git.commitAll(cwd, 'paths'))!;
  assert.deepEqual((await git.diffNameOnly(cwd, base)).sort(), paths.toSorted());
  assert.deepEqual((await git.diffNameOnly(cwd, base, head)).sort(), paths.toSorted());
});
test('merge 충돌 목록은 한글 파일 경로를 그대로 반환하고 merge를 중단한다', async t => {
  const cwd = await repo(t);
  await command(cwd, 'config', 'core.quotePath', 'true');
  await mkdir(join(cwd, 'docs/wiki'), { recursive: true });
  const path = 'docs/wiki/검색.md';
  await writeFile(join(cwd, path), 'base\n');
  await git.commitAll(cwd, 'base');
  await command(cwd, 'checkout', '-b', 'conflict');
  await writeFile(join(cwd, path), 'branch\n');
  await git.commitAll(cwd, 'branch');
  await command(cwd, 'checkout', 'main');
  await writeFile(join(cwd, path), 'main\n');
  const before = await git.commitAll(cwd, 'main');
  assert.deepEqual(await git.merge(cwd, 'conflict'), { ok: false, conflicts: [path] });
  assert.equal(await git.headSha(cwd), before);
  assert.equal(await git.statusPorcelain(cwd), '');
  await assert.rejects(readFile(join(cwd, '.git/MERGE_HEAD')), { code: 'ENOENT' });
});
async function command(cwd: string, ...args: string[]): Promise<string> {
  return (await exec('git', args, { cwd })).stdout.trim();
}
async function repo(t: TestContext): Promise<string> {
  const cwd = await mkdtemp(join(tmpdir(), 'aw-git-'));
  t.after(() => rm(cwd, { recursive: true, force: true }));
  await command(cwd, 'init', '-b', 'main');
  await command(cwd, 'config', 'user.name', 'AW Test');
  await command(cwd, 'config', 'user.email', 'aw@example.invalid');
  return cwd;
}
test('git 조회·commitAll·squash·restore', async t => {
  const cwd = await repo(t);
  assert.equal(await git.isGitRepo(cwd), true);
  assert.equal(await git.hasCommit(cwd), false);
  await writeFile(join(cwd, 'file.txt'), 'base');
  const base = (await git.commitAll(cwd, 'base'))!;
  assert.equal(await git.hasCommit(cwd), true);
  assert.equal(await git.commitAll(cwd, 'empty'), null);
  assert.equal(await git.headSha(cwd), base);
  assert.equal(await git.resolveRef(cwd, 'main'), base);
  assert.equal(await git.resolveRef(cwd, 'missing'), null);
  assert.equal(await git.statusPorcelain(cwd), '');
  await writeFile(join(cwd, 'file.txt'), 'one');
  await git.commitAll(cwd, 'one');
  await writeFile(join(cwd, 'file.txt'), 'two');
  const two = (await git.commitAll(cwd, 'two'))!;
  const squashed = (await git.squash(cwd, base, 'approved'))!;
  assert.notEqual(squashed, two);
  assert.equal(await command(cwd, 'rev-list', '--count', `${base}..HEAD`), '1');
  assert.equal(await git.isAncestor(cwd, base, squashed), true);
  assert.equal(await git.isAncestor(cwd, squashed, base), false);
  assert.deepEqual(await git.diffNameOnly(cwd, base), ['file.txt']);
  assert.deepEqual(await git.diffNameOnly(cwd, base, base), []);
  assert.equal(await git.squash(cwd, squashed, 'empty'), null);
  await writeFile(join(cwd, 'file.txt'), 'dirty');
  await writeFile(join(cwd, 'untracked.txt'), 'new');
  assert.match(await git.statusPorcelain(cwd), /file.txt/);
  await git.restore(cwd, base);
  assert.equal(await git.headSha(cwd), base);
  assert.equal(await readFile(join(cwd, 'file.txt'), 'utf8'), 'base');
  await assert.rejects(readFile(join(cwd, 'untracked.txt')), { code: 'ENOENT' });
  assert.equal(await git.statusPorcelain(cwd), '');
});
test('exclude 중복 방지와 B1 브랜치/worktree 동시 생성', async t => {
  const cwd = await repo(t);
  await writeFile(join(cwd, 'file'), 'base');
  await git.commitAll(cwd, 'base');
  await git.addExcludes(cwd, ['/ai-log/', '/.aw/', '/ai-log/']);
  await git.addExcludes(cwd, ['/ai-log/', '/.aw/']);
  const root = await mkdtemp(join(tmpdir(), 'aw-worktree-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const main = join(root, 'main'), lane = join(root, 'lane-a');
  await git.worktreeAdd(cwd, main, 'aw/id', 'HEAD');
  await git.worktreeAdd(cwd, lane, 'aw/id-lane-a', 'aw/id');
  await git.addExcludes(lane, ['/from-lane/']);
  const excludes = await readFile(join(cwd, '.git/info/exclude'), 'utf8');
  assert.equal(excludes.split('\n').filter(line => line === '/ai-log/').length, 1);
  assert.match(excludes, /\/from-lane\//);
  assert.equal(await command(main, 'branch', '--show-current'), 'aw/id');
  assert.equal(await command(lane, 'branch', '--show-current'), 'aw/id-lane-a');
  await git.worktreeRemove(cwd, lane);
  await git.branchDelete(cwd, 'aw/id-lane-a');
  await git.worktreeRemove(cwd, main);
  await git.branchDelete(cwd, 'aw/id');
});
test('merge 성공과 충돌 목록·abort', async t => {
  const cwd = await repo(t);
  await writeFile(join(cwd, 'file'), 'base\n');
  const base = (await git.commitAll(cwd, 'base'))!;
  await command(cwd, 'checkout', '-b', 'clean');
  await writeFile(join(cwd, 'new'), 'new');
  await git.commitAll(cwd, 'clean');
  await command(cwd, 'checkout', 'main');
  assert.deepEqual(await git.merge(cwd, 'clean'), { ok: true });
  assert.equal((await command(cwd, 'show', '-s', '--format=%P', 'HEAD')).split(' ').length, 2);
  await command(cwd, 'checkout', '-b', 'conflict', base);
  await writeFile(join(cwd, 'file'), 'branch\n');
  await git.commitAll(cwd, 'branch');
  await command(cwd, 'checkout', 'main');
  await writeFile(join(cwd, 'file'), 'main\n');
  const before = await git.commitAll(cwd, 'main');
  assert.deepEqual(await git.merge(cwd, 'conflict'), { ok: false, conflicts: ['file'] });
  assert.equal(await git.headSha(cwd), before);
  assert.equal(await git.statusPorcelain(cwd), '');
  await assert.rejects(readFile(join(cwd, '.git/MERGE_HEAD')), { code: 'ENOENT' });
  await assert.rejects(git.merge(cwd, 'missing'), /git .*merge.*실패:/);
});
